#!/usr/bin/env python3
import os
import sys
import subprocess

SUDO = ''
coin_root = '/opt/coin/hydrogen'
# 获取当前目录位置
current_path = os.getcwd()


def is_root():
    return os.geteuid() == 0

def yes_or_no(msg):
    ans = input(f'{msg}(Y/n):')
    if ans.lower() == 'y' or ans.lower() == 'yes':
        return True
    return False

def root_required():
    global SUDO
    if not is_root():
        SUDO = 'sudo'
        if not yes_or_no("Root Required"):
            return False
        else:
            subprocess.call(['sudo', 'echo', 'Root Permission Required.'])
            return True
    else:
        SUDO = ''
        return True

if __name__ == "__main__":
    # 获取 root 权限
    if not root_required():
        exit(-1)

    if not os.path.exists(coin_root):
        print(f'{coin_root} not exist, create it now.')
        cmd = f'ls /opt/coin && {SUDO} mkdir -p {coin_root}'
        print(f'execute: {cmd}')
        os.system(f'{cmd}')

    pkg_path = os.path.join(current_path, 'package')
    os.system(f'{SUDO} cp -ar {pkg_path}/* {coin_root}')
    print('All Done.')
